"use client";
import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import { zen_maru_gothic } from "./fonts";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <body
          className={
            zen_maru_gothic.className + " bg-white flex flex-col min-h-svh"
          }
        >
          <header>
            <NavBar />
          </header>
          <main className="flex-grow">{children}</main>
          <footer>
            <Footer />
          </footer>
        </body>
      </QueryClientProvider>
    </html>
  );
}
